// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNUnitWebSolution.Data;

#nullable disable

namespace MyNUnitWebSolution.Migrations
{
    [DbContext(typeof(TestHistoryContext))]
    partial class TestHistoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MyNUnitWebSolution.Data.AssemblyRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.ToTable("AssemblyRuns");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.TestOutputLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyRunId");

                    b.ToTable("TestOutputLines");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.AssemblyRun", b =>
                {
                    b.HasOne("MyNUnitWebSolution.Data.TestRun", "TestRun")
                        .WithMany("Assemblies")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.TestOutputLine", b =>
                {
                    b.HasOne("MyNUnitWebSolution.Data.AssemblyRun", "AssemblyRun")
                        .WithMany("Lines")
                        .HasForeignKey("AssemblyRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssemblyRun");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.AssemblyRun", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MyNUnitWebSolution.Data.TestRun", b =>
                {
                    b.Navigation("Assemblies");
                });
#pragma warning restore 612, 618
        }
    }
}
